# Generated by Django 5.0.3 on 2024-05-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0002_rename_notes_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.UUIDField(default='<function uuid4 at 0x0000023E53510FE0>_<django.db.models.fields.CharField>_<django.db.models.fields.related.ForeignKey>_<django.db.models.fields.CharField>_<django.db.models.fields.DateTimeField>', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('STUDLDR', 'Student Leader'), ('STUDENT', 'Students'), ('TEAMLDR', 'Team Leader'), ('PRMRYPI', 'Primary PI'), ('ADVISOR', 'Advisor')], max_length=7),
        ),
    ]
