# Generated by Django 5.0.3 on 2024-05-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0004_alter_note_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.UUIDField(default='<function uuid4 at 0x0000022E73800FE0>_<django.db.models.fields.CharField>_<django.db.models.fields.related.ForeignKey>_<django.db.models.fields.CharField>_<django.db.models.fields.DateTimeField>', editable=False, primary_key=True, serialize=False),
        ),
    ]
