# Generated by Django 5.0.3 on 2024-05-14 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0013_alter_note_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='last_edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
