# Generated by Django 5.0.3 on 2024-06-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0021_alter_user_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
