# Generated by Django 5.0.3 on 2024-05-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0007_alter_note_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
