# Generated by Django 5.0.3 on 2024-05-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0009_alter_note_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.TextField(default='25a0c226558645288066fd2e3d717d82_<django.db.models.fields.related.ForeignKey>', editable=False, primary_key=True, serialize=False),
        ),
    ]
