# Generated by Django 5.0.3 on 2024-05-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0010_alter_note_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.TextField(default='4ec3e881be644ebfa8a1d55796774dfb', editable=False, primary_key=True, serialize=False),
        ),
    ]
