# Generated by Django 5.0.3 on 2024-05-12 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0011_alter_note_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='notebook',
        ),
        migrations.RemoveField(
            model_name='user',
            name='team',
        ),
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.TextField(default='f0de4479a3b041e8b042fc81eeedd97d', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, choices=[('STUDLDR', 'Student Leader'), ('STUDENT', 'Students'), ('PRMRYPI', 'Primary PI'), ('ADVISOR', 'Advisor')], max_length=7, null=True),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=6)),
                ('leader', models.ManyToManyField(blank=True, related_name='leader_of', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, related_name='departments', to=settings.AUTH_USER_MODEL)),
                ('waitlist', models.ManyToManyField(blank=True, related_name='waitlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='dept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='notebook.department'),
        ),
    ]
