# Generated by Django 5.0.3 on 2024-05-14 02:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0012_remove_note_notebook_remove_user_team_alter_note_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
