# Generated by Django 5.0.3 on 2024-05-14 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0014_note_last_edited'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='dept',
            new_name='department',
        ),
    ]
