# Generated by Django 5.0.3 on 2024-05-21 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0016_alter_department_code_alter_department_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='verified',
        ),
    ]
