# Generated by Django 5.0.3 on 2024-06-08 15:17

import django.utils.timezone
import notebook.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0019_attachedimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachedimages',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=notebook.models.upload_images),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, choices=[(3, 'Student Leader'), (1, 'Students'), (2, 'Primary PI'), (2, 'Advisor')], max_length=7, null=True),
        ),
    ]
