# Generated by Django 5.0.3 on 2024-06-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0020_alter_attachedimages_image_alter_user_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.IntegerField(choices=[(3, 'Student Leader'), (1, 'Students'), (2, 'Primary PI'), (2, 'Advisor')], null=True),
        ),
    ]
