# Generated by Django 5.0.3 on 2024-06-12 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0022_alter_note_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.IntegerField(choices=[(3, 'Student Leader'), (1, 'Student'), (2, 'Primary PI'), (2, 'Advisor')], null=True),
        ),
    ]
