# Generated by Django 5.0.3 on 2024-06-12 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0023_alter_user_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.IntegerField(choices=[(3, 'Student Leader'), (2, 'PI/Advisor'), (1, 'Student')], null=True),
        ),
    ]
