# Generated by Django 5.0.3 on 2024-06-12 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0024_alter_user_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
    ]
